apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocontainer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gocontainer
  template:
    metadata:
      labels:
        app: gocontainer
    spec:
      containers:
      - name: gocontainer
        image: localhost/gocontainer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: GOOS
          value: "linux"
        - name: GOARCH
          value: "amd64"

---
apiVersion: v1
kind: Service
metadata:
  name: gocontainer-service
spec:
  selector:
    app: gocontainer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
