apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-tomcat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-tomcat-app
  template:
    metadata:
      labels:
        app: java-tomcat-app
    spec:
      containers:
      - name: java-tomcat-app
        #image: java-tomcat-app:latest
        image: ghcr.io/mattsmith13815/gok8s:main
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
